deploy:
  provider: heroku
  api_key:
    secure: jm2OXj+D1DSBSfqPvMJpeIVUnxOsqe0laH7Lcs6EYCEjVqjzySlqwTPLrUynHhtwdA5LIUjJyOYH+LXLfb8hnxe1PSdmrZNlgBGBmSMvBLwbkPkNtz2Y1ZLUSLkqP7vnIgMHnn1X9AhCMbKxekKCvZAEm096vLyX223t79LasBA=
  app: salty-stream-5695
  on:
    repo: neslom/swept-away
